// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: graphtest/entity.proto

package graphtest

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityEnabled struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntityEnabled) Reset() {
	*x = EntityEnabled{}
	mi := &file_graphtest_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityEnabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityEnabled) ProtoMessage() {}

func (x *EntityEnabled) ProtoReflect() protoreflect.Message {
	mi := &file_graphtest_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntityEnabled) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *EntityEnabled) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EntityEnabled) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EntityEnabled) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type EntityEnabled_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 EntityEnabled_builder) Build() *EntityEnabled {
	m0 := &EntityEnabled{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type EntityDisabled struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntityDisabled) Reset() {
	*x = EntityDisabled{}
	mi := &file_graphtest_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDisabled) ProtoMessage() {}

func (x *EntityDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_graphtest_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntityDisabled) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *EntityDisabled) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EntityDisabled) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EntityDisabled) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type EntityDisabled_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 EntityDisabled_builder) Build() *EntityDisabled {
	m0 := &EntityDisabled{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type EntityDisabledExplicit struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntityDisabledExplicit) Reset() {
	*x = EntityDisabledExplicit{}
	mi := &file_graphtest_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDisabledExplicit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDisabledExplicit) ProtoMessage() {}

func (x *EntityDisabledExplicit) ProtoReflect() protoreflect.Message {
	mi := &file_graphtest_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntityDisabledExplicit) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *EntityDisabledExplicit) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EntityDisabledExplicit) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EntityDisabledExplicit) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type EntityDisabledExplicit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 EntityDisabledExplicit_builder) Build() *EntityDisabledExplicit {
	m0 := &EntityDisabledExplicit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

var File_graphtest_entity_proto protoreflect.FileDescriptor

const file_graphtest_entity_proto_rawDesc = "" +
	"\n" +
	"\x16graphtest/entity.proto\x12\tgraphtest\x1a\torm.proto\"-\n" +
	"\rEntityEnabled\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x05B\x06\xea\x82\x16\x02(\x01R\x02id:\x04\xca\xfc\x15\x00\"(\n" +
	"\x0eEntityDisabled\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x05B\x06\xea\x82\x16\x02(\x01R\x02id\"8\n" +
	"\x16EntityDisabledExplicit\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x05B\x06\xea\x82\x16\x02(\x01R\x02id:\x06\xca\xfc\x15\x02\b\x01BBZ@github.com/protobuf-orm/protobuf-orm/internal/examples/graphtestb\beditionsp\xe8\a"

var file_graphtest_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graphtest_entity_proto_goTypes = []any{
	(*EntityEnabled)(nil),          // 0: graphtest.EntityEnabled
	(*EntityDisabled)(nil),         // 1: graphtest.EntityDisabled
	(*EntityDisabledExplicit)(nil), // 2: graphtest.EntityDisabledExplicit
}
var file_graphtest_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_graphtest_entity_proto_init() }
func file_graphtest_entity_proto_init() {
	if File_graphtest_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphtest_entity_proto_rawDesc), len(file_graphtest_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graphtest_entity_proto_goTypes,
		DependencyIndexes: file_graphtest_entity_proto_depIdxs,
		MessageInfos:      file_graphtest_entity_proto_msgTypes,
	}.Build()
	File_graphtest_entity_proto = out.File
	file_graphtest_entity_proto_goTypes = nil
	file_graphtest_entity_proto_depIdxs = nil
}
