// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: orm/options.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	xxx_hidden_Crud        bool                   `protobuf:"varint,2,opt,name=crud"`
	xxx_hidden_Add         *RpcAdd                `protobuf:"bytes,16,opt,name=add"`
	xxx_hidden_Get         *RpcGet                `protobuf:"bytes,17,opt,name=get"`
	xxx_hidden_Patch       *RpcPatch              `protobuf:"bytes,18,opt,name=patch"`
	xxx_hidden_Erase       *RpcErase              `protobuf:"bytes,19,opt,name=erase"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcOptions) Reset() {
	*x = RpcOptions{}
	mi := &file_orm_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcOptions) ProtoMessage() {}

func (x *RpcOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcOptions) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcOptions) GetCrud() bool {
	if x != nil {
		return x.xxx_hidden_Crud
	}
	return false
}

func (x *RpcOptions) GetAdd() *RpcAdd {
	if x != nil {
		return x.xxx_hidden_Add
	}
	return nil
}

func (x *RpcOptions) GetGet() *RpcGet {
	if x != nil {
		return x.xxx_hidden_Get
	}
	return nil
}

func (x *RpcOptions) GetPatch() *RpcPatch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *RpcOptions) GetErase() *RpcErase {
	if x != nil {
		return x.xxx_hidden_Erase
	}
	return nil
}

func (x *RpcOptions) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RpcOptions) SetCrud(v bool) {
	x.xxx_hidden_Crud = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *RpcOptions) SetAdd(v *RpcAdd) {
	x.xxx_hidden_Add = v
}

func (x *RpcOptions) SetGet(v *RpcGet) {
	x.xxx_hidden_Get = v
}

func (x *RpcOptions) SetPatch(v *RpcPatch) {
	x.xxx_hidden_Patch = v
}

func (x *RpcOptions) SetErase(v *RpcErase) {
	x.xxx_hidden_Erase = v
}

func (x *RpcOptions) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcOptions) HasCrud() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RpcOptions) HasAdd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Add != nil
}

func (x *RpcOptions) HasGet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Get != nil
}

func (x *RpcOptions) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *RpcOptions) HasErase() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Erase != nil
}

func (x *RpcOptions) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

func (x *RpcOptions) ClearCrud() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Crud = false
}

func (x *RpcOptions) ClearAdd() {
	x.xxx_hidden_Add = nil
}

func (x *RpcOptions) ClearGet() {
	x.xxx_hidden_Get = nil
}

func (x *RpcOptions) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

func (x *RpcOptions) ClearErase() {
	x.xxx_hidden_Erase = nil
}

type RpcOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
	// Enables add, get, patch, and erase.
	Crud  *bool
	Add   *RpcAdd
	Get   *RpcGet
	Patch *RpcPatch
	Erase *RpcErase
}

func (b0 RpcOptions_builder) Build() *RpcOptions {
	m0 := &RpcOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	if b.Crud != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Crud = *b.Crud
	}
	x.xxx_hidden_Add = b.Add
	x.xxx_hidden_Get = b.Get
	x.xxx_hidden_Patch = b.Patch
	x.xxx_hidden_Erase = b.Erase
	return m0
}

type MessageOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	xxx_hidden_Rpc         *RpcOptions            `protobuf:"bytes,2,opt,name=rpc"`
	xxx_hidden_Indexes     *[]*Index              `protobuf:"bytes,3,rep,name=indexes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_orm_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageOptions) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *MessageOptions) GetRpc() *RpcOptions {
	if x != nil {
		return x.xxx_hidden_Rpc
	}
	return nil
}

func (x *MessageOptions) GetIndexes() []*Index {
	if x != nil {
		if x.xxx_hidden_Indexes != nil {
			return *x.xxx_hidden_Indexes
		}
	}
	return nil
}

func (x *MessageOptions) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *MessageOptions) SetRpc(v *RpcOptions) {
	x.xxx_hidden_Rpc = v
}

func (x *MessageOptions) SetIndexes(v []*Index) {
	x.xxx_hidden_Indexes = &v
}

func (x *MessageOptions) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MessageOptions) HasRpc() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Rpc != nil
}

func (x *MessageOptions) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

func (x *MessageOptions) ClearRpc() {
	x.xxx_hidden_Rpc = nil
}

type MessageOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
	Rpc      *RpcOptions
	Indexes  []*Index
}

func (b0 MessageOptions_builder) Build() *MessageOptions {
	m0 := &MessageOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	x.xxx_hidden_Rpc = b.Rpc
	x.xxx_hidden_Indexes = &b.Indexes
	return m0
}

type FieldOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	xxx_hidden_Type        Type                   `protobuf:"varint,2,opt,name=type,enum=orm.Type"`
	xxx_hidden_Key         bool                   `protobuf:"varint,5,opt,name=key"`
	xxx_hidden_Unique      bool                   `protobuf:"varint,6,opt,name=unique"`
	xxx_hidden_Nullable    bool                   `protobuf:"varint,7,opt,name=nullable"`
	xxx_hidden_Immutable   bool                   `protobuf:"varint,8,opt,name=immutable"`
	xxx_hidden_Default     *string                `protobuf:"bytes,16,opt,name=default"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_orm_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *FieldOptions) GetType() Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *FieldOptions) GetKey() bool {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return false
}

func (x *FieldOptions) GetUnique() bool {
	if x != nil {
		return x.xxx_hidden_Unique
	}
	return false
}

func (x *FieldOptions) GetNullable() bool {
	if x != nil {
		return x.xxx_hidden_Nullable
	}
	return false
}

func (x *FieldOptions) GetImmutable() bool {
	if x != nil {
		return x.xxx_hidden_Immutable
	}
	return false
}

func (x *FieldOptions) GetDefault() string {
	if x != nil {
		if x.xxx_hidden_Default != nil {
			return *x.xxx_hidden_Default
		}
		return ""
	}
	return ""
}

func (x *FieldOptions) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *FieldOptions) SetType(v Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *FieldOptions) SetKey(v bool) {
	x.xxx_hidden_Key = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *FieldOptions) SetUnique(v bool) {
	x.xxx_hidden_Unique = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *FieldOptions) SetNullable(v bool) {
	x.xxx_hidden_Nullable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *FieldOptions) SetImmutable(v bool) {
	x.xxx_hidden_Immutable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *FieldOptions) SetDefault(v string) {
	x.xxx_hidden_Default = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *FieldOptions) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FieldOptions) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FieldOptions) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FieldOptions) HasUnique() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FieldOptions) HasNullable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *FieldOptions) HasImmutable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *FieldOptions) HasDefault() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *FieldOptions) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

func (x *FieldOptions) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = Type_TYPE_UNSPECIFIED
}

func (x *FieldOptions) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Key = false
}

func (x *FieldOptions) ClearUnique() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Unique = false
}

func (x *FieldOptions) ClearNullable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Nullable = false
}

func (x *FieldOptions) ClearImmutable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Immutable = false
}

func (x *FieldOptions) ClearDefault() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Default = nil
}

type FieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled  *bool
	Type      *Type
	Key       *bool
	Unique    *bool
	Nullable  *bool
	Immutable *bool
	// TODO: Any?
	Default *string
}

func (b0 FieldOptions_builder) Build() *FieldOptions {
	m0 := &FieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Key = *b.Key
	}
	if b.Unique != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Unique = *b.Unique
	}
	if b.Nullable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Nullable = *b.Nullable
	}
	if b.Immutable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Immutable = *b.Immutable
	}
	if b.Default != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Default = b.Default
	}
	return m0
}

type EdgeOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	xxx_hidden_Bind        *Ref                   `protobuf:"bytes,2,opt,name=bind"`
	xxx_hidden_From        *Ref                   `protobuf:"bytes,3,opt,name=from"`
	xxx_hidden_Unique      bool                   `protobuf:"varint,6,opt,name=unique"`
	xxx_hidden_Nullable    bool                   `protobuf:"varint,7,opt,name=nullable"`
	xxx_hidden_Immutable   bool                   `protobuf:"varint,8,opt,name=immutable"`
	xxx_hidden_Default     *string                `protobuf:"bytes,16,opt,name=default"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EdgeOptions) Reset() {
	*x = EdgeOptions{}
	mi := &file_orm_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeOptions) ProtoMessage() {}

func (x *EdgeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EdgeOptions) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *EdgeOptions) GetBind() *Ref {
	if x != nil {
		return x.xxx_hidden_Bind
	}
	return nil
}

func (x *EdgeOptions) GetFrom() *Ref {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *EdgeOptions) GetUnique() bool {
	if x != nil {
		return x.xxx_hidden_Unique
	}
	return false
}

func (x *EdgeOptions) GetNullable() bool {
	if x != nil {
		return x.xxx_hidden_Nullable
	}
	return false
}

func (x *EdgeOptions) GetImmutable() bool {
	if x != nil {
		return x.xxx_hidden_Immutable
	}
	return false
}

func (x *EdgeOptions) GetDefault() string {
	if x != nil {
		if x.xxx_hidden_Default != nil {
			return *x.xxx_hidden_Default
		}
		return ""
	}
	return ""
}

func (x *EdgeOptions) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *EdgeOptions) SetBind(v *Ref) {
	x.xxx_hidden_Bind = v
}

func (x *EdgeOptions) SetFrom(v *Ref) {
	x.xxx_hidden_From = v
}

func (x *EdgeOptions) SetUnique(v bool) {
	x.xxx_hidden_Unique = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *EdgeOptions) SetNullable(v bool) {
	x.xxx_hidden_Nullable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *EdgeOptions) SetImmutable(v bool) {
	x.xxx_hidden_Immutable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *EdgeOptions) SetDefault(v string) {
	x.xxx_hidden_Default = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *EdgeOptions) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EdgeOptions) HasBind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bind != nil
}

func (x *EdgeOptions) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *EdgeOptions) HasUnique() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EdgeOptions) HasNullable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EdgeOptions) HasImmutable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *EdgeOptions) HasDefault() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *EdgeOptions) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

func (x *EdgeOptions) ClearBind() {
	x.xxx_hidden_Bind = nil
}

func (x *EdgeOptions) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *EdgeOptions) ClearUnique() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Unique = false
}

func (x *EdgeOptions) ClearNullable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Nullable = false
}

func (x *EdgeOptions) ClearImmutable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Immutable = false
}

func (x *EdgeOptions) ClearDefault() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Default = nil
}

type EdgeOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled  *bool
	Bind      *Ref
	From      *Ref
	Unique    *bool
	Nullable  *bool
	Immutable *bool
	// TODO: Any?
	Default *string
}

func (b0 EdgeOptions_builder) Build() *EdgeOptions {
	m0 := &EdgeOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	x.xxx_hidden_Bind = b.Bind
	x.xxx_hidden_From = b.From
	if b.Unique != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Unique = *b.Unique
	}
	if b.Nullable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Nullable = *b.Nullable
	}
	if b.Immutable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Immutable = *b.Immutable
	}
	if b.Default != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Default = b.Default
	}
	return m0
}

var File_orm_options_proto protoreflect.FileDescriptor

const file_orm_options_proto_rawDesc = "" +
	"\n" +
	"\x11orm/options.proto\x12\x03orm\x1a\x0form/index.proto\x1a\rorm/ref.proto\x1a\rorm/rpc.proto\x1a\x0eorm/type.proto\"\xc4\x01\n" +
	"\n" +
	"RpcOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04crud\x18\x02 \x01(\bR\x04crud\x12\x1d\n" +
	"\x03add\x18\x10 \x01(\v2\v.orm.RpcAddR\x03add\x12\x1d\n" +
	"\x03get\x18\x11 \x01(\v2\v.orm.RpcGetR\x03get\x12#\n" +
	"\x05patch\x18\x12 \x01(\v2\r.orm.RpcPatchR\x05patch\x12#\n" +
	"\x05erase\x18\x13 \x01(\v2\r.orm.RpcEraseR\x05erase\"u\n" +
	"\x0eMessageOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12!\n" +
	"\x03rpc\x18\x02 \x01(\v2\x0f.orm.RpcOptionsR\x03rpc\x12$\n" +
	"\aindexes\x18\x03 \x03(\v2\n" +
	".orm.IndexR\aindexes\"\xc7\x01\n" +
	"\fFieldOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x1d\n" +
	"\x04type\x18\x02 \x01(\x0e2\t.orm.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x05 \x01(\bR\x03key\x12\x16\n" +
	"\x06unique\x18\x06 \x01(\bR\x06unique\x12\x1a\n" +
	"\bnullable\x18\a \x01(\bR\bnullable\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\x12\x18\n" +
	"\adefault\x18\x10 \x01(\tR\adefault\"\xd1\x01\n" +
	"\vEdgeOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x1c\n" +
	"\x04bind\x18\x02 \x01(\v2\b.orm.RefR\x04bind\x12\x1c\n" +
	"\x04from\x18\x03 \x01(\v2\b.orm.RefR\x04from\x12\x16\n" +
	"\x06unique\x18\x06 \x01(\bR\x06unique\x12\x1a\n" +
	"\bnullable\x18\a \x01(\bR\bnullable\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\x12\x18\n" +
	"\adefault\x18\x10 \x01(\tR\adefaultB,Z*github.com/protobuf-orm/protobuf-orm/ormpbb\beditionsp\xe8\a"

var file_orm_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orm_options_proto_goTypes = []any{
	(*RpcOptions)(nil),     // 0: orm.RpcOptions
	(*MessageOptions)(nil), // 1: orm.MessageOptions
	(*FieldOptions)(nil),   // 2: orm.FieldOptions
	(*EdgeOptions)(nil),    // 3: orm.EdgeOptions
	(*RpcAdd)(nil),         // 4: orm.RpcAdd
	(*RpcGet)(nil),         // 5: orm.RpcGet
	(*RpcPatch)(nil),       // 6: orm.RpcPatch
	(*RpcErase)(nil),       // 7: orm.RpcErase
	(*Index)(nil),          // 8: orm.Index
	(Type)(0),              // 9: orm.Type
	(*Ref)(nil),            // 10: orm.Ref
}
var file_orm_options_proto_depIdxs = []int32{
	4,  // 0: orm.RpcOptions.add:type_name -> orm.RpcAdd
	5,  // 1: orm.RpcOptions.get:type_name -> orm.RpcGet
	6,  // 2: orm.RpcOptions.patch:type_name -> orm.RpcPatch
	7,  // 3: orm.RpcOptions.erase:type_name -> orm.RpcErase
	0,  // 4: orm.MessageOptions.rpc:type_name -> orm.RpcOptions
	8,  // 5: orm.MessageOptions.indexes:type_name -> orm.Index
	9,  // 6: orm.FieldOptions.type:type_name -> orm.Type
	10, // 7: orm.EdgeOptions.bind:type_name -> orm.Ref
	10, // 8: orm.EdgeOptions.from:type_name -> orm.Ref
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_orm_options_proto_init() }
func file_orm_options_proto_init() {
	if File_orm_options_proto != nil {
		return
	}
	file_orm_index_proto_init()
	file_orm_ref_proto_init()
	file_orm_rpc_proto_init()
	file_orm_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_options_proto_rawDesc), len(file_orm_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_options_proto_goTypes,
		DependencyIndexes: file_orm_options_proto_depIdxs,
		MessageInfos:      file_orm_options_proto_msgTypes,
	}.Build()
	File_orm_options_proto = out.File
	file_orm_options_proto_goTypes = nil
	file_orm_options_proto_depIdxs = nil
}
