// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orm/order.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order int32

const (
	Order_ORDER_UNSPECIFIED Order = 0
	Order_ORDER_ASCENDING   Order = 1
	Order_ORDER_ASCEND      Order = 1
	Order_ORDER_ASC         Order = 1
	Order_ORDER_INC         Order = 1
	Order_ORDER_DESCENDING  Order = 2
	Order_ORDER_DESCEND     Order = 2
	Order_ORDER_DESC        Order = 2
	Order_ORDER_DEC         Order = 2
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_UNSPECIFIED",
		1: "ORDER_ASCENDING",
		// Duplicate value: 1: "ORDER_ASCEND",
		// Duplicate value: 1: "ORDER_ASC",
		// Duplicate value: 1: "ORDER_INC",
		2: "ORDER_DESCENDING",
		// Duplicate value: 2: "ORDER_DESCEND",
		// Duplicate value: 2: "ORDER_DESC",
		// Duplicate value: 2: "ORDER_DEC",
	}
	Order_value = map[string]int32{
		"ORDER_UNSPECIFIED": 0,
		"ORDER_ASCENDING":   1,
		"ORDER_ASCEND":      1,
		"ORDER_ASC":         1,
		"ORDER_INC":         1,
		"ORDER_DESCENDING":  2,
		"ORDER_DESCEND":     2,
		"ORDER_DESC":        2,
		"ORDER_DEC":         2,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_order_proto_enumTypes[0].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_orm_order_proto_enumTypes[0]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OrderItem struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Refs  *[]*Ref                `protobuf:"bytes,1,rep,name=refs"`
	xxx_hidden_Order Order                  `protobuf:"varint,2,opt,name=order,enum=orm.Order"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orm_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orm_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrderItem) GetRefs() []*Ref {
	if x != nil {
		if x.xxx_hidden_Refs != nil {
			return *x.xxx_hidden_Refs
		}
	}
	return nil
}

func (x *OrderItem) GetOrder() Order {
	if x != nil {
		return x.xxx_hidden_Order
	}
	return Order_ORDER_UNSPECIFIED
}

func (x *OrderItem) SetRefs(v []*Ref) {
	x.xxx_hidden_Refs = &v
}

func (x *OrderItem) SetOrder(v Order) {
	x.xxx_hidden_Order = v
}

type OrderItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Refs  []*Ref
	Order Order
}

func (b0 OrderItem_builder) Build() *OrderItem {
	m0 := &OrderItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Refs = &b.Refs
	x.xxx_hidden_Order = b.Order
	return m0
}

var File_orm_order_proto protoreflect.FileDescriptor

const file_orm_order_proto_rawDesc = "" +
	"\n" +
	"\x0form/order.proto\x12\x03orm\x1a\rorm/ref.proto\"K\n" +
	"\tOrderItem\x12\x1c\n" +
	"\x04refs\x18\x01 \x03(\v2\b.orm.RefR\x04refs\x12 \n" +
	"\x05order\x18\x02 \x01(\x0e2\n" +
	".orm.OrderR\x05order*\xaf\x01\n" +
	"\x05Order\x12\x15\n" +
	"\x11ORDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fORDER_ASCENDING\x10\x01\x12\x10\n" +
	"\fORDER_ASCEND\x10\x01\x12\r\n" +
	"\tORDER_ASC\x10\x01\x12\r\n" +
	"\tORDER_INC\x10\x01\x12\x14\n" +
	"\x10ORDER_DESCENDING\x10\x02\x12\x11\n" +
	"\rORDER_DESCEND\x10\x02\x12\x0e\n" +
	"\n" +
	"ORDER_DESC\x10\x02\x12\r\n" +
	"\tORDER_DEC\x10\x02\x1a\x02\x10\x01B1Z*github.com/protobuf-orm/protobuf-orm/ormpb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_orm_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orm_order_proto_goTypes = []any{
	(Order)(0),        // 0: orm.Order
	(*OrderItem)(nil), // 1: orm.OrderItem
	(*Ref)(nil),       // 2: orm.Ref
}
var file_orm_order_proto_depIdxs = []int32{
	2, // 0: orm.OrderItem.refs:type_name -> orm.Ref
	0, // 1: orm.OrderItem.order:type_name -> orm.Order
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orm_order_proto_init() }
func file_orm_order_proto_init() {
	if File_orm_order_proto != nil {
		return
	}
	file_orm_ref_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_order_proto_rawDesc), len(file_orm_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_order_proto_goTypes,
		DependencyIndexes: file_orm_order_proto_depIdxs,
		EnumInfos:         file_orm_order_proto_enumTypes,
		MessageInfos:      file_orm_order_proto_msgTypes,
	}.Build()
	File_orm_order_proto = out.File
	file_orm_order_proto_goTypes = nil
	file_orm_order_proto_depIdxs = nil
}
