// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orm.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_orm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         45001,
		Name:          "orm.message",
		Tag:           "bytes,45001,opt,name=message",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         45101,
		Name:          "orm.field",
		Tag:           "bytes,45101,opt,name=field",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EdgeOptions)(nil),
		Field:         45102,
		Name:          "orm.edge",
		Tag:           "bytes,45102,opt,name=edge",
		Filename:      "orm.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional orm.MessageOptions message = 45001;
	E_Message = &file_orm_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional orm.FieldOptions field = 45101;
	E_Field = &file_orm_proto_extTypes[1]
	// optional orm.EdgeOptions edge = 45102;
	E_Edge = &file_orm_proto_extTypes[2]
)

var File_orm_proto protoreflect.FileDescriptor

const file_orm_proto_rawDesc = "" +
	"\n" +
	"\torm.proto\x12\x03orm\x1a google/protobuf/descriptor.proto\x1a\x11orm/options.proto:P\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xc9\xdf\x02 \x01(\v2\x13.orm.MessageOptionsR\amessage:H\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xad\xe0\x02 \x01(\v2\x11.orm.FieldOptionsR\x05field:E\n" +
	"\x04edge\x12\x1d.google.protobuf.FieldOptions\x18\xae\xe0\x02 \x01(\v2\x10.orm.EdgeOptionsR\x04edgeB,Z*github.com/protobuf-orm/protobuf-orm/ormpbb\beditionsp\xe8\a"

var file_orm_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
	(*MessageOptions)(nil),              // 2: orm.MessageOptions
	(*FieldOptions)(nil),                // 3: orm.FieldOptions
	(*EdgeOptions)(nil),                 // 4: orm.EdgeOptions
}
var file_orm_proto_depIdxs = []int32{
	0, // 0: orm.message:extendee -> google.protobuf.MessageOptions
	1, // 1: orm.field:extendee -> google.protobuf.FieldOptions
	1, // 2: orm.edge:extendee -> google.protobuf.FieldOptions
	2, // 3: orm.message:type_name -> orm.MessageOptions
	3, // 4: orm.field:type_name -> orm.FieldOptions
	4, // 5: orm.edge:type_name -> orm.EdgeOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_proto_init() }
func file_orm_proto_init() {
	if File_orm_proto != nil {
		return
	}
	file_orm_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_proto_rawDesc), len(file_orm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_orm_proto_goTypes,
		DependencyIndexes: file_orm_proto_depIdxs,
		ExtensionInfos:    file_orm_proto_extTypes,
	}.Build()
	File_orm_proto = out.File
	file_orm_proto_goTypes = nil
	file_orm_proto_depIdxs = nil
}
