// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: orm/rpc.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	xxx_hidden_Crud        bool                   `protobuf:"varint,2,opt,name=crud"`
	xxx_hidden_Add         *RpcAdd                `protobuf:"bytes,16,opt,name=add"`
	xxx_hidden_Get         *RpcGet                `protobuf:"bytes,17,opt,name=get"`
	xxx_hidden_Patch       *RpcPatch              `protobuf:"bytes,18,opt,name=patch"`
	xxx_hidden_Erase       *RpcErase              `protobuf:"bytes,19,opt,name=erase"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcOptions) Reset() {
	*x = RpcOptions{}
	mi := &file_orm_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcOptions) ProtoMessage() {}

func (x *RpcOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcOptions) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcOptions) GetCrud() bool {
	if x != nil {
		return x.xxx_hidden_Crud
	}
	return false
}

func (x *RpcOptions) GetAdd() *RpcAdd {
	if x != nil {
		return x.xxx_hidden_Add
	}
	return nil
}

func (x *RpcOptions) GetGet() *RpcGet {
	if x != nil {
		return x.xxx_hidden_Get
	}
	return nil
}

func (x *RpcOptions) GetPatch() *RpcPatch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *RpcOptions) GetErase() *RpcErase {
	if x != nil {
		return x.xxx_hidden_Erase
	}
	return nil
}

func (x *RpcOptions) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *RpcOptions) SetCrud(v bool) {
	x.xxx_hidden_Crud = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *RpcOptions) SetAdd(v *RpcAdd) {
	x.xxx_hidden_Add = v
}

func (x *RpcOptions) SetGet(v *RpcGet) {
	x.xxx_hidden_Get = v
}

func (x *RpcOptions) SetPatch(v *RpcPatch) {
	x.xxx_hidden_Patch = v
}

func (x *RpcOptions) SetErase(v *RpcErase) {
	x.xxx_hidden_Erase = v
}

func (x *RpcOptions) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcOptions) HasCrud() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RpcOptions) HasAdd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Add != nil
}

func (x *RpcOptions) HasGet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Get != nil
}

func (x *RpcOptions) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *RpcOptions) HasErase() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Erase != nil
}

func (x *RpcOptions) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

func (x *RpcOptions) ClearCrud() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Crud = false
}

func (x *RpcOptions) ClearAdd() {
	x.xxx_hidden_Add = nil
}

func (x *RpcOptions) ClearGet() {
	x.xxx_hidden_Get = nil
}

func (x *RpcOptions) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

func (x *RpcOptions) ClearErase() {
	x.xxx_hidden_Erase = nil
}

type RpcOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
	// Enables add, get, patch, and erase.
	Crud  *bool
	Add   *RpcAdd
	Get   *RpcGet
	Patch *RpcPatch
	Erase *RpcErase
}

func (b0 RpcOptions_builder) Build() *RpcOptions {
	m0 := &RpcOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	if b.Crud != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Crud = *b.Crud
	}
	x.xxx_hidden_Add = b.Add
	x.xxx_hidden_Get = b.Get
	x.xxx_hidden_Patch = b.Patch
	x.xxx_hidden_Erase = b.Erase
	return m0
}

type RpcAdd struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcAdd) Reset() {
	*x = RpcAdd{}
	mi := &file_orm_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcAdd) ProtoMessage() {}

func (x *RpcAdd) ProtoReflect() protoreflect.Message {
	mi := &file_orm_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcAdd) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcAdd) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RpcAdd) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcAdd) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

type RpcAdd_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
}

func (b0 RpcAdd_builder) Build() *RpcAdd {
	m0 := &RpcAdd{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	return m0
}

type RpcGet struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcGet) Reset() {
	*x = RpcGet{}
	mi := &file_orm_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGet) ProtoMessage() {}

func (x *RpcGet) ProtoReflect() protoreflect.Message {
	mi := &file_orm_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcGet) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcGet) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RpcGet) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcGet) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

type RpcGet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
}

func (b0 RpcGet_builder) Build() *RpcGet {
	m0 := &RpcGet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	return m0
}

type RpcPatch struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcPatch) Reset() {
	*x = RpcPatch{}
	mi := &file_orm_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPatch) ProtoMessage() {}

func (x *RpcPatch) ProtoReflect() protoreflect.Message {
	mi := &file_orm_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcPatch) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcPatch) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RpcPatch) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcPatch) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

type RpcPatch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
}

func (b0 RpcPatch_builder) Build() *RpcPatch {
	m0 := &RpcPatch{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	return m0
}

type RpcErase struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Disabled    bool                   `protobuf:"varint,1,opt,name=disabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcErase) Reset() {
	*x = RpcErase{}
	mi := &file_orm_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcErase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcErase) ProtoMessage() {}

func (x *RpcErase) ProtoReflect() protoreflect.Message {
	mi := &file_orm_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcErase) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *RpcErase) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RpcErase) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RpcErase) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Disabled = false
}

type RpcErase_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Disabled *bool
}

func (b0 RpcErase_builder) Build() *RpcErase {
	m0 := &RpcErase{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	return m0
}

var File_orm_rpc_proto protoreflect.FileDescriptor

const file_orm_rpc_proto_rawDesc = "" +
	"\n" +
	"\rorm/rpc.proto\x12\x03orm\"\xc4\x01\n" +
	"\n" +
	"RpcOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04crud\x18\x02 \x01(\bR\x04crud\x12\x1d\n" +
	"\x03add\x18\x10 \x01(\v2\v.orm.RpcAddR\x03add\x12\x1d\n" +
	"\x03get\x18\x11 \x01(\v2\v.orm.RpcGetR\x03get\x12#\n" +
	"\x05patch\x18\x12 \x01(\v2\r.orm.RpcPatchR\x05patch\x12#\n" +
	"\x05erase\x18\x13 \x01(\v2\r.orm.RpcEraseR\x05erase\"$\n" +
	"\x06RpcAdd\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"$\n" +
	"\x06RpcGet\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"&\n" +
	"\bRpcPatch\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"&\n" +
	"\bRpcErase\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabledB,Z*github.com/protobuf-orm/protobuf-orm/ormpbb\beditionsp\xe8\a"

var file_orm_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orm_rpc_proto_goTypes = []any{
	(*RpcOptions)(nil), // 0: orm.RpcOptions
	(*RpcAdd)(nil),     // 1: orm.RpcAdd
	(*RpcGet)(nil),     // 2: orm.RpcGet
	(*RpcPatch)(nil),   // 3: orm.RpcPatch
	(*RpcErase)(nil),   // 4: orm.RpcErase
}
var file_orm_rpc_proto_depIdxs = []int32{
	1, // 0: orm.RpcOptions.add:type_name -> orm.RpcAdd
	2, // 1: orm.RpcOptions.get:type_name -> orm.RpcGet
	3, // 2: orm.RpcOptions.patch:type_name -> orm.RpcPatch
	4, // 3: orm.RpcOptions.erase:type_name -> orm.RpcErase
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orm_rpc_proto_init() }
func file_orm_rpc_proto_init() {
	if File_orm_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_rpc_proto_rawDesc), len(file_orm_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_rpc_proto_goTypes,
		DependencyIndexes: file_orm_rpc_proto_depIdxs,
		MessageInfos:      file_orm_rpc_proto_msgTypes,
	}.Build()
	File_orm_rpc_proto = out.File
	file_orm_rpc_proto_goTypes = nil
	file_orm_rpc_proto_depIdxs = nil
}
