// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orm/type.proto

package ormpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_TYPE_BOOL        Type = 8
	Type_TYPE_ENUM        Type = 14
	Type_TYPE_INT32       Type = 5
	Type_TYPE_SINT32      Type = 17
	Type_TYPE_UINT32      Type = 13
	Type_TYPE_INT64       Type = 3
	Type_TYPE_SINT64      Type = 18
	Type_TYPE_UINT64      Type = 4
	Type_TYPE_SFIXED32    Type = 15
	Type_TYPE_FIXED32     Type = 7
	Type_TYPE_FLOAT       Type = 2
	Type_TYPE_SFIXED64    Type = 16
	Type_TYPE_FIXED64     Type = 6
	Type_TYPE_DOUBLE      Type = 1
	Type_TYPE_STRING      Type = 9
	Type_TYPE_BYTES       Type = 12
	Type_TYPE_MESSAGE     Type = 11
	Type_TYPE_GROUP       Type = 10
	Type_TYPE_INT         Type = 3
	Type_TYPE_UINT        Type = 4
	Type_TYPE_UUID        Type = 64
	Type_TYPE_TIME        Type = 65
	Type_TYPE_JSON        Type = 66
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		8:  "TYPE_BOOL",
		14: "TYPE_ENUM",
		5:  "TYPE_INT32",
		17: "TYPE_SINT32",
		13: "TYPE_UINT32",
		3:  "TYPE_INT64",
		18: "TYPE_SINT64",
		4:  "TYPE_UINT64",
		15: "TYPE_SFIXED32",
		7:  "TYPE_FIXED32",
		2:  "TYPE_FLOAT",
		16: "TYPE_SFIXED64",
		6:  "TYPE_FIXED64",
		1:  "TYPE_DOUBLE",
		9:  "TYPE_STRING",
		12: "TYPE_BYTES",
		11: "TYPE_MESSAGE",
		10: "TYPE_GROUP",
		// Duplicate value: 3: "TYPE_INT",
		// Duplicate value: 4: "TYPE_UINT",
		64: "TYPE_UUID",
		65: "TYPE_TIME",
		66: "TYPE_JSON",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_BOOL":        8,
		"TYPE_ENUM":        14,
		"TYPE_INT32":       5,
		"TYPE_SINT32":      17,
		"TYPE_UINT32":      13,
		"TYPE_INT64":       3,
		"TYPE_SINT64":      18,
		"TYPE_UINT64":      4,
		"TYPE_SFIXED32":    15,
		"TYPE_FIXED32":     7,
		"TYPE_FLOAT":       2,
		"TYPE_SFIXED64":    16,
		"TYPE_FIXED64":     6,
		"TYPE_DOUBLE":      1,
		"TYPE_STRING":      9,
		"TYPE_BYTES":       12,
		"TYPE_MESSAGE":     11,
		"TYPE_GROUP":       10,
		"TYPE_INT":         3,
		"TYPE_UINT":        4,
		"TYPE_UUID":        64,
		"TYPE_TIME":        65,
		"TYPE_JSON":        66,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_orm_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_orm_type_proto protoreflect.FileDescriptor

const file_orm_type_proto_rawDesc = "" +
	"\n" +
	"\x0eorm/type.proto\x12\x03orm*\x9a\x03\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_BOOL\x10\b\x12\r\n" +
	"\tTYPE_ENUM\x10\x0e\x12\x0e\n" +
	"\n" +
	"TYPE_INT32\x10\x05\x12\x0f\n" +
	"\vTYPE_SINT32\x10\x11\x12\x0f\n" +
	"\vTYPE_UINT32\x10\r\x12\x0e\n" +
	"\n" +
	"TYPE_INT64\x10\x03\x12\x0f\n" +
	"\vTYPE_SINT64\x10\x12\x12\x0f\n" +
	"\vTYPE_UINT64\x10\x04\x12\x11\n" +
	"\rTYPE_SFIXED32\x10\x0f\x12\x10\n" +
	"\fTYPE_FIXED32\x10\a\x12\x0e\n" +
	"\n" +
	"TYPE_FLOAT\x10\x02\x12\x11\n" +
	"\rTYPE_SFIXED64\x10\x10\x12\x10\n" +
	"\fTYPE_FIXED64\x10\x06\x12\x0f\n" +
	"\vTYPE_DOUBLE\x10\x01\x12\x0f\n" +
	"\vTYPE_STRING\x10\t\x12\x0e\n" +
	"\n" +
	"TYPE_BYTES\x10\f\x12\x10\n" +
	"\fTYPE_MESSAGE\x10\v\x12\x0e\n" +
	"\n" +
	"TYPE_GROUP\x10\n" +
	"\x12\f\n" +
	"\bTYPE_INT\x10\x03\x12\r\n" +
	"\tTYPE_UINT\x10\x04\x12\r\n" +
	"\tTYPE_UUID\x10@\x12\r\n" +
	"\tTYPE_TIME\x10A\x12\r\n" +
	"\tTYPE_JSON\x10B\x1a\x02\x10\x01B,Z*github.com/protobuf-orm/protobuf-orm/ormpbb\beditionsp\xe8\a"

var file_orm_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_type_proto_goTypes = []any{
	(Type)(0), // 0: orm.Type
}
var file_orm_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_type_proto_init() }
func file_orm_type_proto_init() {
	if File_orm_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_type_proto_rawDesc), len(file_orm_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_type_proto_goTypes,
		DependencyIndexes: file_orm_type_proto_depIdxs,
		EnumInfos:         file_orm_type_proto_enumTypes,
	}.Build()
	File_orm_type_proto = out.File
	file_orm_type_proto_goTypes = nil
	file_orm_type_proto_depIdxs = nil
}
